name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore Action/PostMediumGitHubAction.sln

      - name: Build
        run: dotnet build Action/PostMediumGitHubAction.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Action/PostMediumGitHubAction.sln --no-restore

      - name: Upload to SonarQube
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"philips-software_post-to-medium-action" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths=coverage.xml
          dotnet build Action/PostMediumGitHubAction.sln
          dotnet test --logger trx --no-restore --verbosity normal --collect:"XPLat Code Coverage" --results-directory "coverage.xml"
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
