name: Create Docker Image

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Images
        uses: philips-software/docker-ci-scripts@main
        with:
          dockerfile: ./Action/Dockerfile
          image-name: post-to-medium-action
          tags: latest ${{ github.ref_name }}
          push-on-git-tag: "true"
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io/philips-software
          GITHUB_ORGANIZATION: philips-software
